### PR TITLE
Support importing posts

### LINKED ISSUE #4: Set revision author on update on the WordPress side

### LINKED ISSUE #61: Support Importing Posts from GitHub
We should support importing posts created on GitHub, as long as they have the basic frontmatter added, e.g. this is an importable post:

```
---
---
I wrote a post.
```

Currently, this is not possible because the controller has gotten out of control and needs to be broken down into several pieces, so this issue includes any notes about the controller refactor.

Notes:
* An Import and Export object should be split off from the controller.
* Some of the post saving can be pushed down into the Post object itself.
* We should include in the docs the default info to include in the YAML frontmatter.
* Add unit tests as we do this

### PR DESCRIPTION
**Pull request by mAAdhaTTah**
Fixes #61. Fixes #4.

This works, so far, but handling the issues raised by #4 continues to be an issue. Generally speaking, I'm not loving the way we're handling authors overall. I'm wondering if maybe we should add a settings for a "default author" to be used in case the author isn't found. Overall, this may require some additional refactoring; I may push some things down from the main plugin class into the controller, and have the controller decide whether to fire the additional export.

### CODE REVIEW

**Comment by mAAdhaTTah** [comment]
I don't know what's going on with Travis, but I've got this working locally. There are definitely some things I'd like to modify about the way this deals with the authors, as well as add unit tests, but this could use a lookover + some testing.

**Comment by mAAdhaTTah** [comment]
I think this is ready to go. Planning on merging and deploying this weekend.

**Comment by mAAdhaTTah** [comment]
Updated the way we're handling authors now. The user can set a default user that WPGHS falls back to when searching for a user fails. Updated the documentation to reflect this change.

**Comment by sivyel** [comment]
how to remove sync for old posts in the repo when first time configure. Which hook need to remove ?

**Comment by mAAdhaTTah** [comment]
@sivyel This should match up posts with their post IDs, if they're aligned between what's in the repo & in the database.

**Comment by sivyel** [comment]
@mAAdhaTTah Actually i'm not using sync process one time push from git to wordpress is enough. If you can help me to sync only one post what we commit from git. Don't sync other existing files from git. Can you help me in that?

**Comment by mAAdhaTTah** [comment]
It won't import anything that doesn't have a post front matter, so the rest of the files shouldn't interfere.

**Comment by sivyel** [comment]
@mAAdhaTTah Rest of the files also have frontmatter format only

**Comment by mAAdhaTTah** [comment]
Not entirely sure this is possible, tbh. I'd have to dig into it.

**Comment by sivyel** [comment]
@mAAdhaTTah can you help on this, only commit which i did need to sync other than existing don't consider

**Comment by mAAdhaTTah** [comment]
Unfortunately, no, I don't really have the time generally and have moved on to other open source projects.

**Pull request merged**
